GET http://localhost:5050/api/v1/user/info/config
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NThmMTY1OTMzNzBlYzE5MTJkMGU3ZTMiLCJ1c2VybmFtZSI6IklzbWFDb3J0R3R6IiwiaWF0IjoxNzAzODc4MzY5LCJleHAiOjE3MDM4ODcwMDl9.m4d-lNVYQFZdiKnKpp203npPP1pNHDi6YkF31I0BTkM